server:
  port: 8081
spring:
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  datasource:
    url: jdbc:postgresql://localhost:5432/TrabFinal?serverTimeZone=ADT
    username: postgres
    password: postdba
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
