insert into medicos (name, gender, dep_id) values ('Human Resources', 'F', 12);
insert into medicos (name, gender, dep_id) values ('Legal', 'F', 20);
insert into medicos (name, gender, dep_id) values ('Services', 'M', 6);
insert into medicos (name, gender, dep_id) values ('Human Resources', 'F', 8);
insert into medicos (name, gender, dep_id) values ('Engineering', 'M', 30);
insert into medicos (name, gender, dep_id) values ('Business Development', 'M', 41);
insert into medicos (name, gender, dep_id) values ('Sales', 'F', 1);
insert into medicos (name, gender, dep_id) values ('Product Management', 'M', 16);
insert into medicos (name, gender, dep_id) values ('Marketing', 'M', 32);
insert into medicos (name, gender, dep_id) values ('Research and Development', 'F', 26);
insert into medicos (name, gender, dep_id) values ('Accounting', 'F', 41);
insert into medicos (name, gender, dep_id) values ('Sales', 'M', 39);
insert into medicos (name, gender, dep_id) values ('Human Resources', 'F', 41);
insert into medicos (name, gender, dep_id) values ('Product Management', 'M', 38);
insert into medicos (name, gender, dep_id) values ('Human Resources', 'F', 22);
insert into medicos (name, gender, dep_id) values ('Services', 'F', 23);
insert into medicos (name, gender, dep_id) values ('Engineering', 'F', 8);
insert into medicos (name, gender, dep_id) values ('Business Development', 'F', 13);
insert into medicos (name, gender, dep_id) values ('Product Management', 'M', 24);
insert into medicos (name, gender, dep_id) values ('Legal', 'F', 48);
insert into medicos (name, gender, dep_id) values ('Product Management', 'F', 1);
insert into medicos (name, gender, dep_id) values ('Training', 'M', 47);
insert into medicos (name, gender, dep_id) values ('Engineering', 'M', 19);
insert into medicos (name, gender, dep_id) values ('Training', 'M', 46);
insert into medicos (name, gender, dep_id) values ('Training', 'M', 41);
insert into medicos (name, gender, dep_id) values ('Engineering', 'M', 16);
insert into medicos (name, gender, dep_id) values ('Services', 'M', 1);
insert into medicos (name, gender, dep_id) values ('Accounting', 'F', 11);
insert into medicos (name, gender, dep_id) values ('Business Development', 'M', 2);
insert into medicos (name, gender, dep_id) values ('Accounting', 'F', 5);
insert into medicos (name, gender, dep_id) values ('Research and Development', 'M', 49);
insert into medicos (name, gender, dep_id) values ('Marketing', 'M', 33);
insert into medicos (name, gender, dep_id) values ('Marketing', 'F', 2);
insert into medicos (name, gender, dep_id) values ('Training', 'M', 39);
insert into medicos (name, gender, dep_id) values ('Services', 'F', 26);
insert into medicos (name, gender, dep_id) values ('Engineering', 'M', 23);
insert into medicos (name, gender, dep_id) values ('Services', 'F', 9);
insert into medicos (name, gender, dep_id) values ('Legal', 'M', 42);
insert into medicos (name, gender, dep_id) values ('Services', 'F', 7);
insert into medicos (name, gender, dep_id) values ('Training', 'F', 49);
insert into medicos (name, gender, dep_id) values ('Accounting', 'F', 36);
insert into medicos (name, gender, dep_id) values ('Research and Development', 'F', 9);
insert into medicos (name, gender, dep_id) values ('Accounting', 'F', 6);
insert into medicos (name, gender, dep_id) values ('Marketing', 'M', 45);
insert into medicos (name, gender, dep_id) values ('Services', 'F', 29);
insert into medicos (name, gender, dep_id) values ('Sales', 'F', 3);
insert into medicos (name, gender, dep_id) values ('Human Resources', 'M', 50);
insert into medicos (name, gender, dep_id) values ('Research and Development', 'F', 15);
insert into medicos (name, gender, dep_id) values ('Services', 'F', 12);
insert into medicos (name, gender, dep_id) values ('Human Resources', 'F', 50);